import Link from 'next/link';
import {Prisma} from '@prisma/client';
import {notFound} from 'next/navigation';
import {db} from '@/lib/db';
import {requireUser} from '@/lib/auth';
import {aiAdapter} from '@/lib/ai';
import {Heading,Badge,Empty,Money} from '@/components/ui';
import {BusinessForm,ServiceForm} from '@/components/business-form';
import {OrdersTable} from '@/components/orders-table';
import {ActionForm} from '@/components/form';
import {settingsAction} from '@/app/actions';
export default async function Dashboard({params,searchParams}:{params:Promise<{path?:string[]}>;searchParams:Promise<{saved?:string;business?:string}>}){
 const u=await requireUser(),{path=[]}=await params,p=await searchParams,section=path[0]||'overview';
 if(section==='businesses'&&path[1]==='new')return <div className="business-editor"><Heading eyebrow="BUILD SOMETHING THAT WORKS" title="Create your business." description="Your expertise, services, and standards. Start with the essentials."/><BusinessForm/></div>;
 if(section==='businesses'&&path[1]){const b=await db.business.findFirst({where:{id:path[1],ownerId:u.id},include:{services:{orderBy:{createdAt:'asc'}}}});if(!b)notFound();return <div className="business-editor"><Heading eyebrow="BUSINESS CONFIGURATION" title={b.name} action={<Link className="button secondary" href={`/b/${b.slug}?preview=1`}>Preview storefront ↗</Link>}/>{p.saved&&<p className="notice" style={{marginBottom:24}}>Business saved.</p>}<BusinessForm business={b}/><div className="section-title"><h2>Services & pricing</h2><Badge>{b.services.length} services</Badge></div>{b.services.map(s=><details key={s.id}><summary>{s.name} · <Money amount={s.price} currency={b.currency}/>{!s.active?' · Inactive':''}</summary><div className="panel"><ServiceForm businessId={b.id} service={s}/></div></details>)}<details open={!b.services.length}><summary>+ Add a service</summary><div className="panel"><ServiceForm businessId={b.id}/></div></details><Link href={`/dashboard/analytics?business=${b.id}`} className="text-link">View business performance ↗</Link></div>;}
 if(section==='settings'){return <><Heading title="Account settings"/><div className="panel"><ActionForm action={settingsAction} submit="Update profile"><label className="field">Display name<input name="name" defaultValue={u.name} minLength={2} maxLength={80} required/></label><label className="field">Email<input value={u.email} disabled readOnly/></label><p className="muted small">Sessions expire after seven days. Sign out on shared devices.</p></ActionForm></div></>;}
 if(section==='integrations'){const ai=aiAdapter();return <><Heading eyebrow="BUSINESS INFRASTRUCTURE" title="Integrations" description="Providers handle the infrastructure. Hoga connects the workflow."/><div className="panel"><div className="row spread"><h2>Moove payments</h2><Badge>{process.env.MOOVE_MODE==='demo'?'Demo mode':'Live integration unavailable'}</Badge></div><p>Payment requests, settlement records, and receipts.</p><p className="notice">{process.env.MOOVE_MODE==='demo'?'Demo payment — no real funds moved. You can test the full order flow.':'Live payments are blocked until a verified Moove API contract is implemented.'}</p><p className="small muted spaced">Live setup requires API documentation, merchant credentials, settlement verification, supported currencies, and webhook authentication details. Secrets are configured on the server.</p></div><div className="panel"><div className="row spread"><h2>AI provider</h2><Badge>{ai.demo?'Deterministic demo':`${ai.provider} / ${ai.model}`}</Badge></div><p>{ai.demo?'No external model is active. Scoping and fulfillment are clearly labelled deterministic samples.':'An external model generates scopes and deliverables. No live research tools are connected.'}</p><p className="small muted">Configure AI_PROVIDER, AI_API_KEY, AI_MODEL, and optionally AI_BASE_URL in your deployment environment.</p></div><div className="panel"><h2>Fulfillment processing</h2><p>Confirmed payments enqueue persistent jobs. A worker or authenticated cron recovers interrupted jobs and retries failures up to three times.</p></div></>;}
 const businesses=await db.business.findMany({where:{ownerId:u.id},include:{services:{orderBy:{price:'asc'}}},orderBy:{createdAt:'desc'}});
 const businessIds=businesses.map(b=>b.id);if(p.business&&!businessIds.includes(p.business))notFound();
 const orders=await db.order.findMany({where:{businessId:p.business||{in:businessIds}},include:{quote:true,payment:true,customer:{select:{id:true,name:true,email:true}}},orderBy:{createdAt:'desc'}});
 const live=orders.filter(o=>o.payment?.mode==='live'&&o.payment.status==='CONFIRMED'),demo=orders.filter(o=>o.payment?.mode==='demo'&&o.payment.status==='CONFIRMED');
 const currencies=[...new Set(live.map(o=>o.currency))];
 const totals=currencies.map(currency=>({currency,total:live.filter(o=>o.currency===currency).reduce((sum,o)=>sum.add(o.amount),new Prisma.Decimal(0))}));
 if(section==='businesses')return <><Heading eyebrow="YOUR PORTFOLIO" title="Businesses" description="Build, configure, and publish your autonomous businesses." action={<Link className="button" href="/dashboard/businesses/new">Create business +</Link>}/><div className="cards">{businesses.map(b=><Link className="business-card" key={b.id} href={`/dashboard/businesses/${b.id}`}><div className="row spread"><div className="avatar">{b.logo||b.name.slice(0,2)}</div><Badge>{b.published?'Published':'Draft'}</Badge></div><div><h3>{b.name}</h3><p className="muted">{b.shortDescription}</p></div><div className="row spread small"><span>{b.services.length} services</span><span>Configure ↗</span></div></Link>)}{!businesses.length&&<Empty title="A business starts with your expertise.">Create your first business to define services, pricing, and agent instructions.</Empty>}</div></>;
 if(section==='services')return <><Heading title="Services" description="Every service has its own scope and pricing boundaries."/>{!businesses.length&&<Empty title="Create a business first"><Link href="/dashboard/businesses/new">Create business ↗</Link></Empty>}{businesses.map(b=><div className="panel" key={b.id}><div className="row spread"><h2>{b.name}</h2><Link className="text-link" href={`/dashboard/businesses/${b.id}`}>Manage services ↗</Link></div>{b.services.map(s=><div className="service-row" key={s.id}><div className="row spread"><h3>{s.name}</h3><Money amount={s.price} currency={b.currency}/></div><p className="muted">{s.description}</p><p className="small">Floor: <Money amount={s.minimum} currency={b.currency}/> · Max discount: {s.maxDiscount}% · Negotiation {s.negotiation?'on':'off'}</p></div>)}</div>)}</>;
 if(section==='orders'){if(path[1]){const {redirect}=await import('next/navigation');if(!orders.some(o=>o.id===path[1]))notFound();redirect(`/orders/${path[1]}`);}return <><Heading title="Orders" description="From accepted quote to final delivery."/><OrdersTable orders={orders}/></>;}
 if(section==='transactions')return <><Heading title="Transactions" description="Payment requests and settlements linked to every order."/>{orders.some(o=>o.payment)?<div className="table-wrap"><table><thead><tr><th>Reference</th><th>Amount</th><th>Status</th><th>Mode</th><th>Receipt</th></tr></thead><tbody>{orders.filter(o=>o.payment).map(o=><tr key={o.id}><td className="metadata">{o.payment!.reference}</td><td><Money amount={o.payment!.amount} currency={o.currency}/></td><td>{o.payment!.status}</td><td>{o.payment!.mode==='demo'?'Demo — no funds moved':'Live'}</td><td><Link href={`/orders/${o.id}/receipt`}>View ↗</Link></td></tr>)}</tbody></table></div>:<Empty title="No transactions yet">Payment activity appears when customers accept quotes.</Empty>}</>;
 if(section==='customers'){const customers=[...new Map(orders.map(o=>[o.customerId,o.customer])).values()];return <><Heading title="Customers" description="Relationships derived from your actual order history."/>{customers.length?<div className="table-wrap"><table><thead><tr><th>Customer</th><th>Orders</th><th>Latest order</th></tr></thead><tbody>{customers.map(c=><tr key={c.id}><td>{c.name}</td><td>{orders.filter(o=>o.customerId===c.id).length}</td><td><Link href={`/orders/${orders.find(o=>o.customerId===c.id)!.id}`}>View ↗</Link></td></tr>)}</tbody></table></div>:<Empty title="No customers yet">Your customer relationships start with the first accepted quote.</Empty>}</>;}
 if(!['overview','analytics'].includes(section))notFound();
 const conversations=await db.conversation.count({where:{businessId:p.business||{in:businessIds}}});
 return <><Heading eyebrow={section==='overview'?'YOUR BUSINESS, AT A GLANCE':'ACTUAL PLATFORM ACTIVITY'} title={section==='overview'?`Good to see you, ${u.name.split(' ')[0]}.`:'Business performance'} description={section==='overview'?'Your businesses keep moving. Here’s where things stand.':'Live revenue excludes demo payments. Currency totals are kept separate.'} action={<Link className="button" href="/dashboard/businesses/new">Create business +</Link>}/>{section==='analytics'&&<form className="filters"><select name="business" aria-label="Business" defaultValue={p.business||''}><option value="">All businesses</option>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><button className="button secondary">Apply filter</button></form>}<div className="metrics"><div className="metric"><p>LIVE REVENUE</p><strong>{totals.length?totals.map(t=><span key={t.currency}><Money amount={t.total} currency={t.currency}/><br/></span>):'No data yet'}</strong><small>Confirmed live payments only</small></div><div className="metric"><p>TOTAL ORDERS</p><strong>{orders.length||'No data yet'}</strong><small>{demo.length} demo payments confirmed</small></div><div className="metric"><p>ACTIVE ORDERS</p><strong>{orders.filter(o=>!['DELIVERED','FAILED','CANCELLED','REFUNDED'].includes(o.state)).length}</strong><small>Accepted through fulfillment</small></div><div className="metric"><p>COMPLETED ORDERS</p><strong>{orders.filter(o=>o.state==='DELIVERED').length}</strong><small>Includes clearly labelled demo orders</small></div></div>{section==='analytics'&&<div className="panel"><h2>Commerce health</h2><dl className="summary-list"><div><dt>Average live order value</dt><dd>{totals.length?totals.map(t=><div key={t.currency}><Money amount={t.total.div(live.filter(o=>o.currency===t.currency).length)} currency={t.currency}/></div>):'No data yet'}</dd></div><div><dt>Confirmed live payment count</dt><dd>{live.length||'No data yet'}</dd></div><div><dt>Moove live payment volume</dt><dd>{totals.length?totals.map(t=><div key={t.currency}><Money amount={t.total} currency={t.currency}/></div>):'No data yet'}</dd></div><div><dt>Repeat live customers</dt><dd>{live.length?[...new Set(live.map(o=>o.customerId))].filter(id=>live.filter(o=>o.customerId===id).length>1).length:'No data yet'}</dd></div><div><dt>Conversation → accepted order</dt><dd>{conversations?`${(orders.length/conversations*100).toFixed(1)}% (${orders.length}/${conversations})`:'No data yet'}</dd></div></dl></div>}<div className="section-title"><h2>Recent orders</h2><Link className="text-link" href="/dashboard/orders">All orders ↗</Link></div><OrdersTable orders={orders.slice(0,8)}/>{!businesses.length&&<div className="panel spaced"><h2>Put your expertise to work.</h2><p className="muted">Create a business, add your first service, and publish when you’re ready.</p><Link href="/dashboard/businesses/new" className="button">Create your first business ↗</Link></div>}</>;
}

